[package]
name = "windows"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "simple_boot",
]

[dependencies]
bootloader = "0.10.12"
spin = "0.9.1"
[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]